-- PROMPTS
INSERT INTO prompts (text, category) VALUES
('My ideal Sunday morning is...', 'lifestyle'),
('I''m weirdly attracted to...', 'personality'),
('The way to win me over is...', 'personality'),
('I''m looking for...', 'relationship'),
('My most controversial opinion is...', 'personality'),
('I geek out on...', 'hobbies'),
('The best travel story I have is...', 'travel'),
('I won''t shut up about...', 'personality'),
('My simple pleasures are...', 'lifestyle'),
('The most spontaneous thing I''ve done is...', 'adventure'),
('My love language is...', 'relationship'),
('I judge people by...', 'values'),
('The last book I loved was...', 'books'),
('The best concert I''ve been to is...', 'music'),
('My favorite way to spend a Friday night is...', 'lifestyle'),
('My friends describe me as...', 'personality'),
('A green flag in a relationship is...', 'relationship'),
('A red flag in a relationship is...', 'relationship'),
('The most interesting place I''ve visited is...', 'travel'),
('My comfort show is...', 'entertainment')
ON CONFLICT DO NOTHING;

-- INTERESTS
INSERT INTO interests (name, category) VALUES
('Photography', 'hobbies'),
('Reading', 'hobbies'),
('Painting', 'hobbies'),
('Cooking', 'hobbies'),
('Gaming', 'hobbies'),
('Gardening', 'hobbies'),
('Writing', 'hobbies'),
('Rock', 'music'),
('Pop', 'music'),
('Jazz', 'music'),
('Classical', 'music'),
('Hip Hop', 'music'),
('Electronic', 'music'),
('Country', 'music'),
('Italian Food', 'food'),
('Mexican Food', 'food'),
('Asian Food', 'food'),
('Vegan Food', 'food'),
('Street Food', 'food'),
('Fitness', 'lifestyle'),
('Yoga', 'lifestyle'),
('Meditation', 'lifestyle'),
('Minimalism', 'lifestyle'),
('Sustainability', 'lifestyle'),
('Football', 'sports'),
('Basketball', 'sports'),
('Tennis', 'sports'),
('Running', 'sports'),
('Cycling', 'sports'),
('Swimming', 'sports'),
('Movies', 'entertainment'),
('TV Shows', 'entertainment'),
('Anime', 'entertainment'),
('Theatre', 'entertainment'),
('Podcasts', 'entertainment'),
('Backpacking', 'travel'),
('Road Trips', 'travel'),
('City Breaks', 'travel'),
('Beach Holidays', 'travel'),
('Nature Trips', 'travel'),
('Cultural Tourism', 'travel'),
('Volunteering', 'other'),
('Animals', 'other'),
('Technology', 'other'),
('Fashion', 'other'),
('Art', 'other'),
('Politics', 'other'),
('Environment', 'other')
ON CONFLICT DO NOTHING;
